### ISSUE TITLE
[RFC] Performing Segmentation Tasks

### ISSUE THREAD

**Issue by BlanchonMarc** [dnouri/skorch#158]
I am starting to work on segmentation problem.

After implementing a method to load my data with the same behaviour as PyTorch but customised I am actually experimenting the same issues using Skorch Library having a feeling that the NeuralNet module allows an easy computation on Classification Tasks but not for Segmentation.

--------------------------------------------------------
 **Experiment n°1:** Using the custom dataloader as input to the fit method

`net.fit(X=Data, y=None)`

_Throwing me error:_ 
```

~/miniconda2/envs/semseg/lib/python3.6/site-packages/torch/nn/functional.py in conv2d(input, weight, bias, stride, padding, dilation, groups)
     82         >>> F.conv2d(inputs, filters, padding=1)
     83     """
---> 84     if input is not None and input.dim() != 4:
     85         raise ValueError("Expected 4D tensor as input, got {}D tensor instead.".format(input.dim()))
     86

AttributeError: 'list' object has no attribute 'dim'
```

* Is X interpreted as a list of Tensor in this case, is there any changes in type till the dataloader return a Tuple ( Input , Label ) of type (torch.FloatTensor, torch.LongTensor)

--------------------------------------------------------
**Experiment n°2:** Separating the Input Image and Target Image as two dataloader

`net.fit(X=X, y=Y)`

Assuming that the training happened correctly, still when calling a callback, there is a safety check about numpy array conversion for the target data:

_Throwing me error:_ 
```

~/miniconda2/envs/semseg/lib/python3.6/site-packages/skorch-0.1.0.post1-py3.6.egg/skorch/callbacks.py in on_epoch_end(self, net, X, y, X_valid, y_valid, **kwargs)
    304             # We allow y_test to be None but the scoring function has
    305             # to be able to deal with it (i.e. called without y_test).
--> 306             y_test = self.target_extractor(y_test)
    307         current_score = self._scoring(net, X_test, y_test)
    308         history.record(self.name_, current_score)

~/miniconda2/envs/semseg/lib/python3.6/site-packages/skorch-0.1.0.post1-py3.6.egg/skorch/utils.py in to_numpy(X)
    101
    102     if not is_torch_data_type(X):
--> 103         raise TypeError("Cannot convert this data type to a numpy array.")
    104
    105     if X.is_cuda:

TypeError: Cannot convert this data type to a numpy array.
```

--------------------------------------------------------
Does my testing implementations makes sense and is my reflection correct? 
Maybe I am missing something about your library and if it is the case let me excuse.
If not, does it makes any sense to have a new fit function parameters to allow a specific behaviour in case of a Segmentation Task ( image , image ) instead of Classification Task ( image, label ) ?

**Comment by benjamin-work** [comment]
Hi Marc,

What are the types for your `X` and `Y` data? Generally, type `Dataset` is not yet supported but will be in the future (see https://github.com/dnouri/skorch/issues/146).

Your second approach already doesn't look bad but it seems that one of the scoring callbacks is causing trouble. Am I right to assume that you used `NeuralNetClassifier`? If that is so, please try `NeuralNet` instead (you have to specify `criterion` in that case). This way, the net doesn't try to calculate the accuracy score, which makes little sense for your task.

If this doesn't help, please add these parameters when initializing your net:

```
net = NeuralNet(
    ...,
    callbacks__train_loss__target_extractor=lambda x: x,
    callbacks__valid_loss__target_extractor=lambda x: x,
)
```
The reason for this is that the error you get is caused by trying to extract your target data `Y`. With the parameters above, that error should be fixed for the moment.

I would assume that the error you reported should no longer occur with these measures. Please report back if the same or another error occurs then.

**Comment by BlanchonMarc** [comment]
Hello Benjamin, and thanks for the fast answer.
I'm actually sorry for my latency in term of answering your good suggestions.

In order to add some more details about my implementation and my intuitions. I was actually trying to use my first implementation till PyTorch is working the same way. Ideally it would work and solve many problem and worries that I will explain later in this post. Unfortunately i wasn't aware of the issue and I did not read it so .. 

----------------------------

I agree that the second experiments looks more sane in order to fit the data management of Skorch but the reason that I do not like the procedure is that I am aware of the memory managements. While doing classification with a batch size of 10 you'll load 10 image at a time on the dataset while in this case we will load 20.
In any case I question the implementation of your library, but being aware of the fact that the segmentation is not necessarily taken into account, I admit that the possibility of improper handling came to my mind . This is surely a bad a priori on my part.

------------------------- 
To clarify my implementation details you can check anything on my github repo : https://github.com/BlanchonMarc/vibotorch/tree/marc_ws_server on the brach marc_ws_server. 

The implementation is for the moment more or less DIY so to avoid getting bored I'll do a little summary and if the need is there I'll let you see the code.

**The Data handler is implemented this way _(Implementation in vibotorch/database/dataloaderSegmentation.py)_**

`class ImageFolderSegmentation(Dataset)`

In order to make the second implementation separating X and Y? I just copied and made a return of one single value instead of a tuple.

**The fit function and the net is instantiated this way _(vibotorch/test/dataloader/trainSkorch.py)_**

```
n_classes = 12

network = SegNet(in_channels=3, n_classes=n_classes)
network.init_encoder()

network.cuda()
epochs = [200]
lrs = [0.001]

net = skorch.NeuralNet(
    module=network,
    criterion=torch.nn.CrossEntropyLoss,
    max_epochs=10,
    lr=0.1,
    train_split=None,
    use_cuda=True,
    batch_size=10,
    callbacks=None
)

net.fit(X=X, y=Y)
```

------------------------------------------

And also about your remark:

> This way, the net doesn't try to calculate the accuracy score, which makes little sense for your task.

In fact accuracy score is a way of checking the convergence, segmentation such as classification loss are convex (if I'm not wrong), through the iterative process the idea is to minimize ( or maximize depending on the computation ) the loss. 
From this point of view we are also using metrics in order to check sanity and also to be able to compare and save the models. This is the case used in my code and the reason of the implementation of a metric function that allow a comparison and a save of the model state ( **vibotorch/utils/metrics.py** ). 
I agree with you that we can just make an assumption and say " we train for N epochs " and we are looking for the results at the end which is the behaviour of a typical black box. The idea was to avoid this kind of approach but if necessary then...

--------------------------------------

I'm also providing another remark, i'm a bit scared by the fact that i'm giving two datasets, the shuffle keep the symmetric indexes or does it shuffle both separately in the case of X and y separated?

Thank you for your feedback, i'll try your solution when my server memory will be available and give you feedback. This post was to clarify some points and give you a proper overview of the usage of Skorch Library.

**Comment by BenjaminBossan** [comment]
> While doing classification with a batch size of 10 you'll load 10 image at a time on the dataset while in this case we will load 20.

In any case, to make a forward step, you will have to load the 10 input images and the 10 targets at some point, so I don't believe there is a difference either way.

Your goal, if I see it correctly, is to load the images *lazily* during the training. This is not well supported by skorch and as I said earlier, with the upcoming support for datasets as input data, this will change.

> In fact accuracy score is a way of checking the convergence

There are 2 reasons why accuracy is not well suited for segmentation:
* sklearn's `accuracy_score` assumes the target to be 1-dim class labels, which is not true here
* typically the targets in segmentation are heavily biased towards false/background, which leads to a very high accuracy when just prediction false all the time

There are more suitable metrics, e.g. [dice score](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient).

> i'm a bit scared by the fact that i'm giving two datasets, the shuffle keep the symmetric indexes

skorch does not do any shuffling. Instead, this is delegated to pytorch's `DataLoader`. To activate shuffling, initiate the net with `iterator_train__shuffle=True`. The `DataLoader` will make sure to shuffle your data consistently.

> i'll try your solution when my server memory will be available and give you feedback

Please do that.

**Comment by BlanchonMarc** [comment]
Hello everyone, 
I actually find a opportunity to test the solution provided.


Unfortunately, an error remains to be solved, and after looking a little on my side, I still can not understand how this error can happen.

```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
~/Github/vibotorch/procedures/routine/trainSkorch.py in <module>()
    128 # xfin = x.unsqueeze(0)
    129 # yfin = y.unsqueeze(0)
--> 130 net.fit(X=X, y=Y)

~/Github/skorch/skorch/net.py in fit(self, X, y, **fit_params)
    664             self.initialize()
    665 
--> 666         self.partial_fit(X, y, **fit_params)
    667         return self
    668 

~/Github/skorch/skorch/net.py in partial_fit(self, X, y, classes, **fit_params)
    627         self.notify('on_train_begin')
    628         try:
--> 629             self.fit_loop(X, y, **fit_params)
    630         except KeyboardInterrupt:
    631             pass

~/Github/skorch/skorch/net.py in fit_loop(self, X, y, epochs, **fit_params)
    576 
    577             if X_valid is None:
--> 578                 self.notify('on_epoch_end', **on_epoch_kwargs)
    579                 continue
    580 

~/Github/skorch/skorch/net.py in notify(self, method_name, **cb_kwargs)
    288         getattr(self, method_name)(self, **cb_kwargs)
    289         for _, cb in self.callbacks_:
--> 290             getattr(cb, method_name)(self, **cb_kwargs)
    291 
    292     # pylint: disable=unused-argument

~/Github/skorch/skorch/callbacks.py in on_epoch_end(self, net, X, y, X_valid, y_valid, **kwargs)
    305             # to be able to deal with it (i.e. called without y_test).
    306             y_test = self.target_extractor(y_test)
--> 307         current_score = self._scoring(net, X_test, y_test)
    308         history.record(self.name_, current_score)
    309 

~/Github/skorch/skorch/callbacks.py in _scoring(self, net, X_test, y_test)
    146             y_test=y_test,
    147             scorer=scorer,
--> 148             is_multimetric=False,
    149         )
    150         return scores

~/miniconda3/envs/work/lib/python3.5/site-packages/sklearn/model_selection/_validation.py in _score(estimator, X_test, y_test, scorer, is_multimetric)
    505             score = scorer(estimator, X_test)
    506         else:
--> 507             score = scorer(estimator, X_test, y_test)
    508 
    509         if hasattr(score, 'item'):

~/Github/skorch/skorch/net.py in train_loss_score(net, X, y)
     30     losses = net.history[-1, 'batches', :, 'train_loss']
     31     batch_sizes = net.history[-1, 'batches', :, 'train_batch_size']
---> 32     return np.average(losses, weights=batch_sizes)
     33 
     34 

~/miniconda3/envs/work/lib/python3.5/site-packages/numpy/lib/function_base.py in average(a, axis, weights, returned)
   1138         if np.any(scl == 0.0):
   1139             raise ZeroDivisionError(
-> 1140                 "Weights sum to zero, can't be normalized")
   1141 
   1142         avg = np.multiply(a, wgt, dtype=result_dtype).sum(axis)/scl

ZeroDivisionError: Weights sum to zero, can't be normalized

```

My dataset is perfectly working with PyTorch so apparently there is a sanity check that is performed and I'm not able to pass through.

Thanks for your help and if still you/we are not able to figure out what to do, i'll try to implement by myself the functionalities that I am interested in.

**Comment by BlanchonMarc** [comment]
Hello, after double checking everything, this size problem was coming from access right to the dataset .. 
A stupid mistake. Now everything works fine by following the new input parameters specified in Benjamin's answer. I thank you and if another error appears, it will not be on the dataset nor the process of this one then I will open another issue. I thank you for your help and I close this issue.

PS: Good library and maybe for people interested in segmentation you should add a doc to these two additions of callbacks in the pipeline to avoid having similar issues.

**Comment by BenjaminBossan** [comment]
> Good library and maybe for people interested in segmentation you should add a doc to these two additions of callbacks in the pipeline to avoid having similar issues.

Thank you. I will try add an image segmentation example when I have time (https://github.com/dnouri/skorch/issues/160).
